Repository certimate-go/certimate, pull requests merged in 2024-11, with the labels that each got.

#327 fixed: instance not found when deploying tencent COS
  internal/deployer/tencent_clb.go
  internal/deployer/tencent_cos.go
Labels: bug

#328 bugfix #324
  ui/src/components/certimate/DeployToTencentCLB.tsx
Labels: bug

#329 bugfix #326
  internal/deployer/aliyun_clb.go
  internal/pkg/core/uploader/providers/aliyun-slb/aliyun_slb.go
Labels: bug

#331 bugfix #330
  internal/deployer/qiniu_cdn.go
Labels: bug

#333 feat: 使系统设置中的消息推送设置列表打开后能够关闭
  ui/src/pages/setting/Notify.tsx
Labels: enhancement

#337 fix switch-case syntax error
  internal/deployer/aliyun_clb.go
  internal/pkg/core/uploader/providers/aliyun-slb/aliyun_slb.go
Labels: bug

#339 feat: add volcengine dns provider and add volcengine live deployer
  README.md
  README_EN.md
  go.mod
  go.sum
  internal/applicant/applicant.go
  internal/applicant/volcengine.go
  internal/deployer/deployer.go
  internal/deployer/volcengine_live.go
  internal/domain/access.go
  internal/pkg/core/uploader/providers/volcengine-live/volcengine_live.go
  migrations/1731463526_updated_access.go
  ui/public/imgs/providers/volcengine.svg
  ui/src/components/certimate/AccessEditDialog.tsx
  ui/src/components/certimate/AccessVolcengineForm.tsx
  ui/src/components/certimate/DeployEditDialog.tsx
  ui/src/components/certimate/DeployToVolcengineLive.tsx
  ui/src/domain/access.ts
  ui/src/domain/domain.ts
  ui/src/i18n/locales/en/nls.common.json
  ui/src/i18n/locales/zh/nls.common.json
Labels: enhancement

#342 feat: add volcengine cdn deployer
  README.md
  README_EN.md
  internal/deployer/deployer.go
  internal/deployer/volcengine_cdn.go
  internal/deployer/volcengine_live.go
  internal/pkg/core/uploader/providers/volcengine-cdn/volcengine_cdn.go
  ui/src/components/certimate/DeployEditDialog.tsx
  ui/src/components/certimate/DeployToVolcengineCDN.tsx
  ui/src/domain/domain.ts
  ui/src/i18n/locales/en/nls.common.json
  ui/src/i18n/locales/zh/nls.common.json
Labels: enhancement

#346 feat: add deployer BytePlus CDN
  go.mod
  go.sum
  internal/deployer/byteplus_cdn.go
  internal/deployer/deployer.go
  internal/domain/access.go
  internal/pkg/core/uploader/providers/byteplus-cdn/byteplus_cdn.go
  migrations/1731872250_add_byteplus.go
  ui/public/imgs/providers/byteplus.svg
  ui/src/components/certimate/AccessByteplusForm.tsx
  ui/src/components/certimate/AccessEditDialog.tsx
  ui/src/components/certimate/DeployEditDialog.tsx
  ui/src/components/certimate/DeployToByteplusCDN.tsx
  ui/src/domain/access.ts
  ui/src/domain/domain.ts
  ui/src/i18n/locales/en/nls.common.json
  ui/src/i18n/locales/zh/nls.common.json
Labels: enhancement

#340 fix: reapply when domain list changed
  internal/deployer/tencent_cdn.go
  internal/domains/deploy.go
Labels: enhancement, help wanted
