Repository certimate-go/certimate, pull requests merged in 2025-06, with the labels that each got.

#742 fix: wangsu get certificate list api error #741
  internal/pkg/sdk3rd/wangsu/certificate/api.go
Labels: bug, pr: ready to merge

#755 Support duplicating workflow nodes or branches
  internal/workflow/node-processor/execute_failure_node.go
  internal/workflow/node-processor/execute_success_node.go
  internal/workflow/node-processor/start_node.go
  ui/src/components/workflow/node/ExecuteResultNode.tsx
  ui/src/components/workflow/node/UnknownNode.tsx
  ui/src/components/workflow/node/_SharedNode.tsx
  ui/src/domain/workflow.ts
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
  ui/src/stores/workflow/index.ts
Labels: enhancement, pr: ready to merge

#761 new providers
  go.mod
  go.sum
  internal/applicant/providers.go
  internal/deployer/providers.go
  internal/domain/access.go
  internal/domain/provider.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/aliyun-esa/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/baiducloud/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/constellix/constellix.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/dnsla/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/dynv6/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/gname/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/jdcloud/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/tencentcloud-eo/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/ucloud-udnr/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/ucloud-udnr/ucloud_udnr.go
  internal/pkg/core/deployer/providers/aws-cloudfront/aws_cloudfront.go
  internal/pkg/core/deployer/providers/aws-iam/aws_iam.go
  internal/pkg/core/deployer/providers/ssh/ssh.go
  internal/pkg/core/uploader/providers/aws-acm/aws_acm.go
  internal/pkg/core/uploader/providers/aws-iam/aws_iam.go
  internal/pkg/sdk3rd/ucloud/udnr/apis.go
  internal/pkg/sdk3rd/ucloud/udnr/client.go
  internal/pkg/sdk3rd/ucloud/udnr/models.go
  migrations/1748959200_upgrade.go
  ui/public/imgs/providers/constellix.png
  ui/src/components/access/AccessForm.tsx
  ui/src/components/access/AccessFormConstellixConfig.tsx
  ui/src/components/access/AccessFormSSHConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigForm.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormAWSCloudFrontConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormAWSIAMConfig.tsx
  ui/src/domain/access.ts
  ui/src/domain/provider.ts
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/en/nls.provider.json
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.access.json
  ui/src/i18n/locales/zh/nls.provider.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
Labels: enhancement, pr: ready to merge

#779 build: keep release files as before
  .github/workflows/release.yml
Labels: pr: ready to merge

#782 bugfix
  internal/pkg/core/deployer/providers/aliyun-ga/aliyun_ga.go
  internal/pkg/core/deployer/providers/tencentcloud-eo/tencentcloud_eo.go
  ui/src/components/workflow/node/DeployNodeConfigFormTencentCloudEOConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormTencentCloudSSLDeployConfig.tsx
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
  ui/src/utils/validators.ts
Labels: bug, pr: ready to merge

#789 feat(ui): support deleting email input box auto-complete items #174
  ui/src/components/workflow/node/ApplyNodeConfigForm.tsx
  ui/src/stores/contact/index.ts
Labels: enhancement, pr: ready to merge

#796 fixed 1panel system ssl deploy
  internal/pkg/core/deployer/providers/1panel-console/1panel_console.go
  internal/pkg/sdk3rd/1panel/api.go
  internal/pkg/sdk3rd/1panel/client.go
Labels: enhancement, pr: ready to merge

#799 bugfix
  internal/pkg/utils/map/getter.go
Labels: bug, pr: ready to merge

#802 chore(ui): define version constant
  ui/src/domain/version.ts
  ui/types/vite-env.d.ts
  ui/vite.config.ts
Labels: pr: ready to merge

#818 feat: support Profiles Extension
  internal/applicant/applicant.go
  internal/applicant/providers.go
  internal/domain/workflow.go
  ui/src/components/workflow/node/ApplyNodeConfigForm.tsx
  ui/src/domain/workflow.ts
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
Labels: enhancement, pr: ready to merge

#822 bugfix
  ui/src/components/access/AccessFormCacheFlyConfig.tsx
Labels: bug, pr: ready to merge
