Repository certimate-go/certimate, pull requests merged in 2025-04, with the labels that each got.

#583 feat(notify): add pushplus
  internal/domain/notify.go
  internal/notify/providers.go
  internal/pkg/core/notifier/notifier.go
  internal/pkg/core/notifier/providers/pushplus/pushplus.go
  internal/pkg/core/notifier/providers/pushplus/pushplus_test.go
  ui/src/components/notification/NotifyChannelEditForm.tsx
  ui/src/components/notification/NotifyChannelEditFormPushPlusFields.tsx
  ui/src/domain/settings.ts
  ui/src/i18n/locales/en/nls.common.json
  ui/src/i18n/locales/en/nls.settings.json
  ui/src/i18n/locales/zh/nls.common.json
  ui/src/i18n/locales/zh/nls.settings.json
Labels: enhancement

#578 Support cloudflare zone api token
  internal/applicant/providers.go
  internal/domain/access.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/cloudflare/cloudflare.go
  ui/src/components/access/AccessFormCloudflareConfig.tsx
  ui/src/domain/access.ts
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/zh/nls.access.json
Labels: enhancement

#587 bugfix
  internal/pkg/core/deployer/providers/gcore-cdn/gcore_cdn.go
  internal/pkg/core/deployer/providers/volcengine-alb/volcengine_alb.go
  internal/pkg/core/deployer/providers/volcengine-clb/volcengine_clb.go
  migrations/1742209200_upgrade.go
  ui/src/components/workflow/WorkflowRuns.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormVolcEngineALBConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormVolcEngineCLBConfig.tsx
  ui/src/domain/provider.ts
  ui/src/i18n/locales/en/nls.provider.json
  ui/src/i18n/locales/en/nls.settings.json
  ui/src/i18n/locales/en/nls.workflow.runs.json
  ui/src/i18n/locales/zh/nls.common.json
  ui/src/i18n/locales/zh/nls.provider.json
  ui/src/i18n/locales/zh/nls.settings.json
  ui/src/i18n/locales/zh/nls.workflow.runs.json
Labels: bug

#607 feat: support pushover as notification
  internal/domain/notify.go
  internal/notify/providers.go
  internal/pkg/core/notifier/providers/pushover/pushover.go
  internal/pkg/core/notifier/providers/pushover/pushover_test.go
  ui/src/components/notification/NotifyChannelEditForm.tsx
  ui/src/components/notification/NotifyChannelEditFormPushoverFields.tsx
  ui/src/domain/settings.ts
  ui/src/i18n/locales/en/nls.common.json
  ui/src/i18n/locales/en/nls.settings.json
  ui/src/i18n/locales/zh/nls.common.json
  ui/src/i18n/locales/zh/nls.settings.json
Labels: enhancement

#604 feat(notify): add mattermost
  internal/domain/notify.go
  internal/notify/providers.go
  internal/pkg/core/notifier/providers/mattermost/mattermost.go
  internal/pkg/core/notifier/providers/mattermost/mattermost_test.go
  ui/src/components/notification/NotifyChannelEditForm.tsx
  ui/src/components/notification/NotifyChannelEditFormMattermostFields.tsx
  ui/src/domain/settings.ts
  ui/src/i18n/locales/en/nls.common.json
  ui/src/i18n/locales/en/nls.settings.json
  ui/src/i18n/locales/zh/nls.common.json
  ui/src/i18n/locales/zh/nls.settings.json
Labels: enhancement

#596 bugfix: tencent cloud ecdn deploy error
  internal/pkg/core/deployer/providers/tencentcloud-ecdn/tencentcloud_ecdn.go
Labels: bug

#610 feat: support bunny as dns and cdn provider
  go.mod
  go.sum
  internal/applicant/providers.go
  internal/deployer/providers.go
  internal/domain/access.go
  internal/domain/provider.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/bunny/bunny.go
  internal/pkg/core/deployer/providers/bunny-cdn/bunny_cdn.go
  internal/pkg/core/deployer/providers/bunny-cdn/bunny_cdn_test.go
  internal/pkg/vendors/bunny-sdk/api.go
  internal/pkg/vendors/bunny-sdk/client.go
  internal/pkg/vendors/bunny-sdk/models.go
  migrations/1744459000_upgrade.go
  ui/public/imgs/providers/bunny.svg
  ui/src/components/access/AccessForm.tsx
  ui/src/components/access/AccessFormBunnyConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigForm.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormBunnyCDNConfig.tsx
  ui/src/domain/access.ts
  ui/src/domain/provider.ts
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/en/nls.provider.json
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.access.json
  ui/src/i18n/locales/zh/nls.provider.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
Labels: enhancement, pr: ready to merge

#621 Fix Azure KeyVault bug & Support custom certificate name in Azure KeyVault
  internal/deployer/providers.go
  internal/pkg/core/deployer/providers/azure-keyvault/azure_keyvault.go
  internal/pkg/core/uploader/providers/azure-keyvault/azure_keyvault.go
  internal/pkg/core/uploader/providers/azure-keyvault/azure_keyvault_test.go
  ui/src/components/workflow/node/DeployNodeConfigFormAzureKeyVaultConfig.tsx
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
Labels: bug, pr: ready to merge

#625 修复火山云证书上传获取空值的bug
  internal/pkg/core/uploader/providers/volcengine-certcenter/volcengine_certcenter.go
Labels: bug, pr: ready to merge

#629 new providers
  go.mod
  go.sum
  internal/deployer/providers.go
  internal/domain/provider.go
  internal/pkg/core/deployer/providers/1panel-site/1panel_site.go
  internal/pkg/core/deployer/providers/1panel-site/1panel_site_test.go
  internal/pkg/core/deployer/providers/1panel-site/consts.go
  internal/pkg/core/deployer/providers/aliyun-apigw/aliyun_apigw.go
  internal/pkg/core/deployer/providers/aliyun-apigw/aliyun_apigw_test.go
  internal/pkg/core/deployer/providers/aliyun-apigw/consts.go
  internal/pkg/vendors/1panel-sdk/api.go
  internal/pkg/vendors/1panel-sdk/models.go
  ui/src/components/workflow/node/DeployNodeConfigForm.tsx
  ui/src/components/workflow/node/DeployNodeConfigForm1PanelSiteConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormAliyunAPIGWConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormCdnflyConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormLocalConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormSSHConfig.tsx
  ui/src/domain/provider.ts
  ui/src/i18n/locales/en/nls.provider.json
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.provider.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
Labels: enhancement, pr: ready to merge

#640 field type conversion
  go.mod
  go.sum
  internal/pkg/core/applicant/acme-dns-01/lego-providers/baiducloud/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/cmcccloud/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/dnsla/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/dynv6/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/gname/internal/lego.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/jdcloud/internal/lego.go
  internal/pkg/core/deployer/providers/azure-keyvault/azure_keyvault.go
  internal/pkg/core/deployer/providers/huaweicloud-cdn/huaweicloud_cdn.go
  internal/pkg/core/deployer/providers/huaweicloud-elb/huaweicloud_elb.go
  internal/pkg/core/deployer/providers/huaweicloud-waf/huaweicloud_waf.go
  internal/pkg/core/deployer/providers/wangsu-cdnpro/wangsu_cdnpro.go
  internal/pkg/core/uploader/providers/azure-keyvault/azure_keyvault.go
  internal/pkg/core/uploader/providers/huaweicloud-elb/huaweicloud_elb.go
  internal/pkg/core/uploader/providers/huaweicloud-scm/huaweicloud_scm.go
  internal/pkg/core/uploader/providers/huaweicloud-waf/huaweicloud_waf.go
  internal/pkg/sdk3rd/huaweicloud/cast.go
  internal/pkg/utils/type/assert.go
  internal/pkg/utils/type/cast.go
  migrations/1744459000_upgrade.go
  migrations/1745308800_upgrade.go
  ui/package-lock.json
  ui/package.json
  ui/src/components/workflow/node/DeployNodeConfigFormLocalConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormSSHConfig.tsx
Labels: bug, enhancement
