Repository certimate-go/certimate, pull requests merged in 2025-05, with the labels that each got.

#670 new providers
  go.mod
  go.sum
  internal/applicant/providers.go
  internal/deployer/providers.go
  internal/domain/access.go
  internal/domain/provider.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/powerdns/powerdns.go
  internal/pkg/core/deployer/providers/1panel-console/1panel_console.go
  internal/pkg/core/deployer/providers/1panel-site/1panel_site.go
  internal/pkg/core/deployer/providers/baotapanel-console/baotapanel_console.go
  internal/pkg/core/deployer/providers/baotapanel-site/baotapanel_site.go
  internal/pkg/core/deployer/providers/cdnfly/cdnfly.go
  internal/pkg/core/deployer/providers/cdnfly/cdnfly_test.go
  internal/pkg/core/deployer/providers/goedge/goedge.go
  internal/pkg/core/deployer/providers/goedge/goedge_test.go
  internal/pkg/core/deployer/providers/proxmoxve/proxmoxve.go
  internal/pkg/core/deployer/providers/proxmoxve/proxmoxve_test.go
  internal/pkg/core/deployer/providers/safeline/safeline.go
  internal/pkg/sdk3rd/cdnfly/client.go
  internal/pkg/sdk3rd/goedge/client.go
  ui/public/imgs/providers/proxmoxve.svg
  ui/src/components/access/AccessForm.tsx
  ui/src/components/access/AccessForm1PanelConfig.tsx
  ui/src/components/access/AccessFormBaotaPanelConfig.tsx
  ui/src/components/access/AccessFormCdnflyConfig.tsx
  ui/src/components/access/AccessFormGoEdgeConfig.tsx
  ui/src/components/access/AccessFormPowerDNSConfig.tsx
  ui/src/components/access/AccessFormProxmoxVEConfig.tsx
  ui/src/components/access/AccessFormSafeLineConfig.tsx
  ui/src/components/access/AccessFormWebhookConfig.tsx
  ui/src/components/provider/DeploymentProviderPicker.tsx
  ui/src/components/workflow/node/DeployNodeConfigForm.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormProxmoxVEConfig.tsx
  ui/src/domain/access.ts
  ui/src/domain/provider.ts
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/en/nls.provider.json
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.access.json
  ui/src/i18n/locales/zh/nls.provider.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
Labels: enhancement, pr: ready to merge

#679 bugfix #672
  internal/pkg/core/deployer/providers/gcore-cdn/gcore_cdn.go
Labels: bug, pr: ready to merge

#684 enhance & bugfix
  internal/deployer/providers.go
  internal/domain/access.go
  internal/pkg/core/deployer/providers/aliyun-clb/aliyun_clb.go
  internal/pkg/core/deployer/providers/edgio-applications/edgio_applications.go
  internal/pkg/core/deployer/providers/gcore-cdn/gcore_cdn.go
  internal/pkg/core/deployer/providers/goedge/goedge.go
  internal/pkg/core/deployer/providers/local/local.go
  internal/pkg/core/deployer/providers/ssh/ssh.go
  internal/pkg/core/deployer/providers/webhook/webhook.go
  internal/pkg/sdk3rd/goedge/api.go
  internal/pkg/sdk3rd/goedge/client.go
  internal/pkg/utils/cert/extractor.go
  migrations/1747314000_upgrade.go
  ui/package-lock.json
  ui/package.json
  ui/src/components/CodeInput.tsx
  ui/src/components/TextFileInput.tsx
  ui/src/components/access/AccessFormGoEdgeConfig.tsx
  ui/src/components/access/AccessFormKubernetesConfig.tsx
  ui/src/components/access/AccessFormSSHConfig.tsx
  ui/src/components/access/AccessFormWebhookConfig.tsx
  ui/src/components/certificate/CertificateDetail.tsx
  ui/src/components/notification/NotifyTemplate.tsx
  ui/src/components/provider/AccessProviderPicker.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormLocalConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormSSHConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormTencentCloudSSLDeployConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormWebhookConfig.tsx
  ui/src/components/workflow/node/NotifyNodeConfigForm.tsx
  ui/src/components/workflow/node/NotifyNodeConfigFormWebhookConfig.tsx
  ui/src/components/workflow/node/UploadNodeConfigForm.tsx
  ui/src/domain/access.ts
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/en/nls.common.json
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.access.json
  ui/src/i18n/locales/zh/nls.common.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
  ui/src/pages/AuthLayout.tsx
  ui/src/pages/ConsoleLayout.tsx
  ui/src/utils/browser.ts
Labels: bug, enhancement

#689 new providers
  go.mod
  go.sum
  internal/applicant/providers.go
  internal/deployer/providers.go
  internal/domain/access.go
  internal/domain/provider.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/netcup/netcup.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/netlify/netlify.go
  internal/pkg/core/deployer/providers/aws-acm/aws_acm.go
  internal/pkg/core/deployer/providers/azure-keyvault/azure_keyvault.go
  internal/pkg/core/deployer/providers/baishan-cdn/baishan_cdn.go
  internal/pkg/core/deployer/providers/baotapanel-site/baotapanel_site.go
  internal/pkg/core/deployer/providers/cachefly/cachefly.go
  internal/pkg/core/deployer/providers/edgio-applications/edgio_applications.go
  internal/pkg/core/deployer/providers/gcore-cdn/gcore_cdn.go
  internal/pkg/core/deployer/providers/netlify-site/netlify_site.go
  internal/pkg/core/deployer/providers/netlify-site/netlify_site_test.go
  internal/pkg/core/deployer/providers/wangsu-cdnpro/wangsu_cdnpro.go
  internal/pkg/core/uploader/providers/aws-acm/aws_acm.go
  ui/public/imgs/providers/netcup.png
  ui/public/imgs/providers/netlify.png
  ui/src/components/access/AccessForm.tsx
  ui/src/components/access/AccessFormNetcupConfig.tsx
  ui/src/components/access/AccessFormNetlifyConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigForm.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormAWSACMConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormAzureKeyVaultConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormNetlifySiteConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormSSHConfig.tsx
  ui/src/domain/access.ts
  ui/src/domain/provider.ts
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/en/nls.provider.json
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.access.json
  ui/src/i18n/locales/zh/nls.provider.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
Labels: enhancement, pr: ready to merge

#699 feat: ssh jump server support (#49) (#95)
  internal/deployer/providers.go
  internal/domain/access.go
  internal/pkg/core/deployer/providers/ssh/ssh.go
  ui/src/components/access/AccessFormSSHConfig.tsx
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/zh/nls.access.json
Labels: enhancement, pr: ready to merge

#714 bugfix
  internal/deployer/providers.go
  internal/domain/access.go
  internal/domain/workflow.go
  internal/pkg/core/applicant/acme-dns-01/lego-providers/aliyun-esa/aliyun_esa.go
  internal/pkg/core/deployer/providers/ssh/ssh.go
  internal/pkg/core/deployer/providers/tencentcloud-cdn/tencentcloud_cdn.go
  internal/pkg/core/deployer/providers/tencentcloud-clb/tencentcloud_clb.go
  internal/pkg/core/deployer/providers/tencentcloud-cos/tencentcloud_cos.go
  internal/pkg/core/deployer/providers/tencentcloud-ecdn/tencentcloud_ecdn.go
  internal/pkg/core/deployer/providers/tencentcloud-ssl-deploy/tencentcloud_ssl_deploy.go
  ui/src/components/access/AccessFormSSHConfig.tsx
  ui/src/components/access/AccessFormTelegramBotConfig.tsx
  ui/src/components/workflow/node/NotifyNodeConfigFormTelegramBotConfig.tsx
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/zh/nls.access.json
Labels: bug, pr: ready to merge

#727 new providers
  README.md
  README_EN.md
  internal/deployer/providers.go
  internal/domain/access.go
  internal/domain/provider.go
  internal/pkg/core/deployer/providers/unicloud-webhost/unicloud_webhost.go
  internal/pkg/core/deployer/providers/unicloud-webhost/unicloud_webhost_test.go
  internal/pkg/sdk3rd/dcloud/unicloud/api.go
  internal/pkg/sdk3rd/dcloud/unicloud/client.go
  internal/pkg/sdk3rd/dcloud/unicloud/models.go
  ui/public/imgs/providers/unicloud.png
  ui/src/components/access/AccessForm.tsx
  ui/src/components/access/AccessFormUniCloudConfig.tsx
  ui/src/components/access/AccessFormUpyunConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigForm.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormUniCloudWebHostConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormUpyunCDNConfig.tsx
  ui/src/components/workflow/node/DeployNodeConfigFormUpyunFileConfig.tsx
  ui/src/domain/access.ts
  ui/src/domain/provider.ts
  ui/src/i18n/locales/en/nls.access.json
  ui/src/i18n/locales/en/nls.provider.json
  ui/src/i18n/locales/en/nls.workflow.nodes.json
  ui/src/i18n/locales/zh/nls.access.json
  ui/src/i18n/locales/zh/nls.provider.json
  ui/src/i18n/locales/zh/nls.workflow.nodes.json
Labels: enhancement, pr: ready to merge
